format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$nodejs\
$time\
$cmd_duration\
$character"""

[nodejs]
format = 'via [$symbol($version )]($style) '
style = 'green'

[directory]
truncation_length = 3
truncation_symbol = '…/'
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "on [$symbol$branch]($style)"
style = "bold purple"
symbol = " "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
style = "white"
format = "[$time]($style) "