format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$nodejs\
$shell\
$time\
$cmd_duration\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[ ❯](purple)"
error_symbol = "[ ❯](red)"
vimcmd_symbol = "[ ❮](green)"

[git_branch]
format = "on [[$symbol$branch](purple bg:#1d2230)]($style)"
style = "bold purple"
symbol = " "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[nodejs]
format = 'via [$symbol($version)]($style) '
style = 'green'
